// Vercel build step: write config.js from the VERITAS_API_URL project setting.
//
//   vercel env add VERITAS_API_URL production     (e.g. https://veritas-api.fly.dev)
//
// Unset means same-origin, which is only right when FastAPI serves the page.
import { writeFileSync } from "node:fs";

const url = (process.env.VERITAS_API_URL || "").trim().replace(/\/+$/, "");
// The page is served over HTTPS, and browsers block calls from an HTTPS page
// to an HTTP API (mixed content). Fail the build rather than ship a dead page.
if (url && !/^https:\/\/[^\s/]+/.test(url)) {
  console.error(`VERITAS_API_URL must be an https:// URL, got: ${url}`);
  process.exit(1);
}
writeFileSync(
  new URL("./config.js", import.meta.url),
  "// generated by build-config.mjs -- do not edit on the deployment\n" +
    `window.VERITAS_API = window.VERITAS_API || ${JSON.stringify(url)};\n`,
);
console.log(`config.js -> ${url || "(same origin)"}`);
